### ISSUE TITLE
Bruikbaarheid: formulier in oude browsers

### ISSUE THREAD

**Issue by MicheleNL** [EmielZuurbier/CTTR#10]
Photo albums vallen over het formulier heen, waardoor dit formulier niet in te vullen is (IE11). Kijk of je dit ook met flexbox op kunt lossen.

**Comment by EmielZuurbier** [comment]
Ik heb dit niet kunnen testen, maar ik denk dat deze opgelost is met de rest van de oplossingen.

**Comment by MicheleNL** [comment]
Hi Emiel! 

Het ziet er inmiddels wel iets beter uit in IE11, maar een deel van je formulier valt nu buiten de viewport. 
In het eerste college van Vasilis noemt hij een aantal manieren hoe je websites kunt testen in oudere browsers, check deze nog eventjes.
![screen shot 2016-02-09 at 14 17 19](https://cloud.githubusercontent.com/assets/13998672/12917185/440d7db0-cf38-11e5-9e48-3fc74f601376.png)
