### ISSUE TITLE
Bruikbaarheid: formulier in oude browsers / deel 2

### ISSUE THREAD

**Issue by MicheleNL** [EmielZuurbier/CTTR#15]
Kan jouw closed issues helaas niet reopenen. 

Je formulier valt nog steeds buiten de viewport in Internet Explorer 11. 
Check ook nog even mijn reply in het vorige issue

<img width="530" alt="screen shot 2016-02-12 at 15 48 32" src="https://cloud.githubusercontent.com/assets/13998672/13010091/57b9c3d6-d1a0-11e5-9162-d74825ac492d.png">

**Comment by EmielZuurbier** [comment]
Ik heb de `flex-direction: row;` gewijzigd naar `flex-direction: column;`. Ook zat er een `min-width` op de label. Deze is er af gehaald.
