### ISSUE TITLE
Role attributen

### ISSUE THREAD

**Issue by MicheleNL** [EmielZuurbier/CTTR#18]
Ik zie dat je al een role attribute gebruikt, goed!

Echter zie ik ook: role="close"
Het is goed om te weten dat roles attributen voorgedefinieerd zijn en dat je hier niet alles in kunt stoppen wat je wil. Bekijk even welke je wel kunt gebruiken en waar ze voor staan.

**Comment by EmielZuurbier** [comment]
Goed dat je dat opnoemt. Ik heb bij de knop een class gebruikt in plaats van de role attribute.
