### ISSUE TITLE
Relatieve units

### ISSUE THREAD

**Issue by MicheleNL** [EmielZuurbier/CTTR#5]
Geen relatieve units gebruikt voor breedtes, hoogtes etc. Kijk hier nog even naar, en ga ook na waarom dit problematisch kan zijn.

**Comment by EmielZuurbier** [comment]
Deze had ik inderdaad op een SVG element geplaatst, om deze mee te laten schalen met de tekst van de `figcaption`. Deze waarde is nu in px
