### ISSUE TITLE
Selectors kunnen beknopter.

### ISSUE THREAD

**Issue by MicheleNL** [EmielZuurbier/CTTR#6]
Selectors kunnen misschien nog wel beknopter. Kijk of je het met minder lange selectoren ook af kunt, met het oog op specificity.
(wat nu als je je **`figure`** in een ander element dan een **`article`** ook die style wil laten hebben? En ook: `body > header nav ul li a`). Wanneer je elementen generiek styled kun je ze makkelijker hergebruiken.

**Comment by EmielZuurbier** [comment]
Selectors beknopter gemaakt!
